In [3]:
from pandas_datareader.data import Options
import pandas_datareader.data as web
import numpy as np
import pandas as pd
import datetime
import matplotlib.pyplot as plt
%matplotlib inline
from __future__ import division

In [9]:
amzn = Options('AMZN', 'yahoo')
amzn.expiry_dates

[datetime.date(2017, 11, 24),
 datetime.date(2017, 12, 1),
 datetime.date(2017, 12, 8),
 datetime.date(2017, 12, 15),
 datetime.date(2017, 12, 22),
 datetime.date(2017, 12, 29),
 datetime.date(2018, 1, 5),
 datetime.date(2018, 1, 19),
 datetime.date(2018, 2, 16),
 datetime.date(2018, 3, 16),
 datetime.date(2018, 4, 20),
 datetime.date(2018, 6, 15),
 datetime.date(2018, 7, 20),
 datetime.date(2018, 9, 21),
 datetime.date(2019, 1, 18),
 datetime.date(2019, 6, 21),
 datetime.date(2020, 1, 17)]

In [20]:
expiry = datetime.date(2018, 2, 16)
amzn.get_call_data(expiry=expiry)[['Last','Vol']].head(10)

                                              Last   Vol
Strike Expiry     Type Symbol
740.0  2018-02-16 call AMZN180216C00740000  384.38   1.0
760.0  2018-02-16 call AMZN180216C00760000  353.95   3.0
800.0  2018-02-16 call AMZN180216C00800000  331.00   2.0
825.0  2018-02-16 call AMZN180216C00825000  275.78   3.0
840.0  2018-02-16 call AMZN180216C00840000  247.98   1.0
855.0  2018-02-16 call AMZN180216C00855000  243.95  10.0
865.0  2018-02-16 call AMZN180216C00865000  265.75  16.0
875.0  2018-02-16 call AMZN180216C00875000  268.86   1.0
880.0  2018-02-16 call AMZN180216C00880000  209.35   4.0
885.0  2018-02-16 call AMZN180216C00885000  203.90   1.0

In [28]:
amzn_calls = amzn.get_put_data(expiry=expiry)[['Last','Vol']]
amzn_calls.head(10)

                                            Last  Vol
Strike Expiry     Type Symbol
740.0  2018-02-16 put  AMZN180216P00740000  0.60  1.0
760.0  2018-02-16 put  AMZN180216P00760000  3.58  6.0
780.0  2018-02-16 put  AMZN180216P00780000  1.51  5.0
800.0  2018-02-16 put  AMZN180216P00800000  1.36  3.0
805.0  2018-02-16 put  AMZN180216P00805000  2.11  2.0
810.0  2018-02-16 put  AMZN180216P00810000  2.24  4.0
815.0  2018-02-16 put  AMZN180216P00815000  1.18  1.0
820.0  2018-02-16 put  AMZN180216P00820000  1.27  3.0
825.0  2018-02-16 put  AMZN180216P00825000  1.33  8.0
830.0  2018-02-16 put  AMZN180216P00830000  1.50  3.0

The output above is similar to the one on pages 304-306.

In [29]:
amzn_puts = amzn.get_put_data(expiry=expiry)[['Last','Vol']]
amzn_puts.head(10)

                                            Last  Vol
Strike Expiry     Type Symbol
740.0  2018-02-16 put  AMZN180216P00740000  0.60  1.0
760.0  2018-02-16 put  AMZN180216P00760000  3.58  6.0
780.0  2018-02-16 put  AMZN180216P00780000  1.51  5.0
800.0  2018-02-16 put  AMZN180216P00800000  1.36  3.0
805.0  2018-02-16 put  AMZN180216P00805000  2.11  2.0
810.0  2018-02-16 put  AMZN180216P00810000  2.24  4.0
815.0  2018-02-16 put  AMZN180216P00815000  1.18  1.0
820.0  2018-02-16 put  AMZN180216P00820000  1.27  3.0
825.0  2018-02-16 put  AMZN180216P00825000  1.33  8.0
830.0  2018-02-16 put  AMZN180216P00830000  1.50  3.0

<div style='color:red'> Calculations on pages between 308 and 330 have been skipped for the time being.</div>